#ifndef __CMT2119B_PARAMS_H
#define __CMT2119B_PARAMS_H

#include <stdint.h>

/*
 * Important:
 * Do not copy cmt2300a_params.h directly.
 *
 * This file must be generated by RFPDK with:
 * Part Number: CMT2119B
 *
 * Before RFPDK parameters are ready, keep these arrays empty.
 * The driver framework can compile, but RF transmission may not work correctly.
 */

static const uint8_t g_cmt2119b_cmt_bank[] = {
};

static const uint8_t g_cmt2119b_system_bank[] = {
};

static const uint8_t g_cmt2119b_frequency_bank[] = {
};

static const uint8_t g_cmt2119b_data_rate_bank[] = {
};

static const uint8_t g_cmt2119b_baseband_bank[] = {
};

static const uint8_t g_cmt2119b_tx_bank[] = {
};

#define CMT2119B_CMT_BANK_SIZE          ((uint8_t)sizeof(g_cmt2119b_cmt_bank))
#define CMT2119B_SYSTEM_BANK_SIZE       ((uint8_t)sizeof(g_cmt2119b_system_bank))
#define CMT2119B_FREQUENCY_BANK_SIZE    ((uint8_t)sizeof(g_cmt2119b_frequency_bank))
#define CMT2119B_DATA_RATE_BANK_SIZE    ((uint8_t)sizeof(g_cmt2119b_data_rate_bank))
#define CMT2119B_BASEBAND_BANK_SIZE     ((uint8_t)sizeof(g_cmt2119b_baseband_bank))
#define CMT2119B_TX_BANK_SIZE           ((uint8_t)sizeof(g_cmt2119b_tx_bank))

#endif
